name: Built-In Functions Test

on:
  workflow_dispatch:
    inputs:
      string_input:
        description: 'string_input: Enter a string value'
        type: string
        default: 'Hello, World'
        required: false
      string_prefix:
        description: 'string_prefix: Enter a string prefix to match'
        type: string
        default: 'Hello'
        required: false
      string_suffix:
        description: 'string_suffix: Enter a string suffix to match'
        type: string
        default: 'World'
        required: false

env:
  YELLOW: "\e[33m"
  LT_BLUE: "\e[0;94m"
  ENDCOLOR: "\e[0m"
  FAKE_SECRET: "This is a placeholder for a secret value"

jobs:
    built-in-functions-test:
        name: 'Strings: Built-In Functions'
        runs-on: ubuntu-latest
        steps:
            - name: Print String input value
              run: |
                echo -e "Input string value = ${YELLOW}${{ inputs.string_input }}${ENDCOLOR}!"
            
            - name: String starts with string_prefix
              if: startsWith(inputs.string_input, inputs.string_prefix)
              run: |
                echo -e "This job ran because ${LT_BLUE}string_input${ENDCOLOR} starts with '${YELLOW}${{ inputs.string_prefix }}${ENDCOLOR}!'"
            
            - name: String ends with string_suffix
              if: endsWith(inputs.string_input, inputs.string_suffix)
              run: |
                echo -e "This job ran because string_input ends with '${YELLOW}${{ inputs.string_suffix }}${ENDCOLOR}!'"

            - name: Add mask
              run: |
                echo -e "FAKE_SECRET = $FAKE_SECRET"
                echo "Masking FAKE_SECRET!"
                echo "::add-mask::$FAKE_SECRET"
                echo "$FAKE_SECRET

