name: Built-In Functions Test

on:
  workflow_dispatch:
    inputs:
      string_input:
        description: 'string_input: Enter a string value'
        type: string
        default: 'Hello, World'
        required: false
      string_prefix:
        description: 'string_prefix: Enter a string prefix to match'
        type: string
        default: 'Hello'
        required: false
      string_suffix:
        description: 'string_suffix: Enter a string suffix to match'
        type: string
        default: 'World'
        required: false

env:
  YELLOW: "\e[33m"
  LT_BLUE: "\e[0;94m"
  ENDCOLOR: "\e[0m"
  FAKE_SECRET: "This is a placeholder for a secret value"

jobs:
    built-in-functions-test:
        name: 'Strings: Built-In Functions'
        runs-on: ubuntu-latest
        steps:
            - name: Print String input value
              run: |
                echo -e "Input string value = ${YELLOW}${{ inputs.string_input }}${ENDCOLOR}!"
            
            - name: String starts with string_prefix
              if: startsWith(inputs.string_input, inputs.string_prefix)
              run: |
                echo -e "This job ran because ${LT_BLUE}string_input${ENDCOLOR} starts with '${YELLOW}${{ inputs.string_prefix }}${ENDCOLOR}!'"
            
            - name: String ends with string_suffix
              if: endsWith(inputs.string_input, inputs.string_suffix)
              run: |
                echo -e "This job ran because string_input ends with '${YELLOW}${{ inputs.string_suffix }}${ENDCOLOR}!'"

            - name: Add mask and show result
              run: |
                echo -e "FAKE_SECRET = $FAKE_SECRET"
                echo "Masking FAKE_SECRET!"
                echo "::add-mask::$FAKE_SECRET"
                echo "FAKE_SECRET = $FAKE_SECRET"

            - name: This job proves add-mask only needs to be used once per job
              run: |
                echo "FAKE_SECRET = $FAKE_SECRET"

            - name: Test GITHUB_STEP_SUMMARY
              run: |
                echo "This is a summary for the *Strings: Built-In Functions* job." >> $GITHUB_STEP_SUMMARY
                echo "This text is generated by writing to the GITHUB_STEP_SUMMARY file." >> $GITHUB_STEP_SUMMARY
      
            - name: Test GITHUB_STEP_SUMMARY in different step
              id: test_step_summary_different_step
              run: |
                echo "This text is also generated by writing to the GITHUB_STEP_SUMMARY file, but was done in a different step (id: \`test_step_summary_different_step\`) than the two previous lines." >> $GITHUB_STEP_SUMMARY
                echo "In the same step, *here's some malformatted markdown (no ending star character to denote italics)" >> $GITHUB_STEP_SUMMARY

            - name: Test GITHUB_STEP_SUMMARY in different step, again!
              id: test_step_summary_different_step_2
              run: |
                echo "*This line* doesn't have the malformatted markdown since it's in a different step (id: \`test_step_summary_different_step_2\`).  " >> $GITHUB_STEP_SUMMARY
                echo "The italics in the above line work, even though there was no closing star two lines above this." >> $GITHUB_STEP_SUMMARY
      
    add-mask-proof:
      name: "Strings: Prove Add Mask Doesn't Persist Across Jobs"
      runs-on: ubuntu-latest
      steps: 
        - name: Show that FAKE_SECRET is not masked in this job
          run: |
            echo -e "FAKE_SECRET = ${YELLOW}$FAKE_SECRET${ENDCOLOR}!"

        - name: Test GITHUB_STEP_SUMMARY
          run: |
            echo "This is a summary for the *Strings: Prove Add Mask Doesn't Persist Across Jobs* job." >> $GITHUB_STEP_SUMMARY
            echo "This text is generated by writing to the GITHUB_STEP_SUMMARY file." >> $GITHUB_STEP_SUMMARY
      