# Say I have a Github Actions workflow job that functions as a status check. 
# This workflow is fired whenever a pull request is opened or synchronized. 
# The workflow will use Python to look at all comments in the HTML, then filter those comments out into an array based on
#  if the comment has the text "TODO" in it. Comments with the text "TODO" in them can be referred to as "'TODO' comments'. 

# A script in the workflow will look at each "TODO" comment and check via pattern matching for a string like "TTNF-1234". 

name: Cache Experiments

on:
  
    workflow_dispatch:
        inputs:
            use-cache:
                description: "Use the cache"
                required: true
                type: boolean
                default: false
            use-dummy-html:
                description: "Take HTML file from testing/html-checks/html"
                required: true
                type: boolean
                default: true
            verbose:
                description: "Adds more debug statements"
                type: boolean
                required: false
                default: false


    workflow_call:
        inputs:
            use-cache:
                description: "Use the cache"
                required: true
                type: boolean
                default: false
            verbose:
                description: "Adds more debug statements"
                type: boolean
                required: false
                default: false

# Do something like Github CLI command to get array of changed filenames from PR
# First check if there's any .html files in the array. If there isn't exit early with success
# To really do that though maybe have two jobs: "html-exists", "cache-experiment-job"
#  cache-experiment-job --> if html-exists.outputs.there-are-html-files == "true"
env:
    GH_TOKEN: ${{ secrets.github_token }}

jobs:

    html-exists:
        name: "Check for HTML files"
        runs-on: ubuntu-latest
        env:
            PR_NUMBER: ${{ github.event.pull_request.number }}
        outputs: 
            # General format steps.<step-id>.outputs.<var written to GITHUB_OUTPUT>
            html-files-present: ${{ steps.check-for-html-files.outputs.html-files-present }}
            html-filenames: ${{ steps.check-for-html-files.outputs.html-filenames }}

        steps:

            - name: "Checkout repo"
              uses: actions/checkout@v4

            - name: "Manual trigger: Use dummy HTML"
              if: inputs.use-dummy-html == true
              run: |
                echo "Using the following files from testing/html-checks/html"
                echo "ttn-frontend-fake-main-03032026.html"

            - name: "Assess PR Changed Files for *.html"
              id: check-for-html-files
              run: |
                html_files_found="false"
                html_filenames_str=""
                if [ "${{ github.event_name }}" == "something" ]
                then 
                    echo "HEY"
                    # PR #9 in ttn-workflows has 2 .html files in it
                    echo "PR_NUMBER=9" >> $GITHUB_ENV
                fi
                # Use process substitution to have jq output be treated as stdin for mapfile. (use Github CLI command below to get file info (obj array)), then jq to get just the "path" from each obj. Use -r to remove double quotes from values otherwise they will be present in the string  )
                mapfile -t changed_filenames < <(gh pr view $PR_NUMBER --json files | jq -r '.files[].path')
                [ "${{ inputs.verbose }}" == "true" ] && echo "About to start HTML file search..." || :
                for changed_filename in "${changed_filenames[@]}"
                do
                    [ "${{ inputs.verbose }}" == "true" ] && echo "changed_filename=${changed_filename}" || :
                    if [[ "$changed_filename" == *".html" ]] 
                    then
                        echo "HIT!"
                        html_files_found='true'
                        html_filenames_str+="${changed_filename},"
                    fi
                done
                echo "html_filenames_str = ${html_filenames_str}"
                echo "html-filenames=${html_filenames_str}" >> "$GITHUB_OUTPUT"
                echo "html_files_found = ${html_files_found}"
                echo "html-files-present=${html_files_found}" >> "$GITHUB_OUTPUT"
            

    cache-experiment-job:
        name: "HTML Checks (example of cache usage)"
        runs-on: ubuntu-latest
        needs: html-exists
        if: needs.html-exists.outputs.html-files-present == 'true'
        steps:
            
            - name: "Checkout repo"
              uses: actions/checkout@v4

            - name: "Echo vars"
              run: echo "${{ needs.html-exists.outputs.html-filenames }}"

            - name: "temp early exit"
              run: exit 1

            # actions/setup-python makes a virtual environment for you and it's already active, so usually no need to do things like "python m venv .venv" or "source .venv/bin/activate"
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"

            # Caches persist for 7 days. TODO move this comment somewhere I dunno where else to put it 
            - name: "Install dependencies using actions/cache"
              id: cache-dependencies
              if: inputs.use-cache
              uses: actions/cache@v4
              with: 
                #  ~/.cache/pip is where TODO
                path: ~/.cache/pip
                key: stop-asking-me-to-fill-all-this-in

            - name: Install dependencies manually
              run: |
                echo "TBD"
                # pip install -r ./scripts/html-checks/requirements.txt

            - name: Call script
              run: |
                echo "blablbala"
                # python html-checks/script.py