# Say I have a Github Actions workflow job that functions as a status check. 
# This workflow is fired whenever a pull request is opened or synchronized. 
# The workflow will use Python to look at all comments in the HTML, then filter those comments out into an array based on
#  if the comment has the text "TODO" in it. Comments with the text "TODO" in them can be referred to as "'TODO' comments'. 

# A script in the workflow will look at each "TODO" comment and check via pattern matching for a string like "TTNF-1234". 

name: Cache Experiments

on:
  
    workflow_dispatch:
        inputs:
            use-cache:
                description: "Use the cache"
                required: true
                type: boolean
                default: false
            use-dummy-html:
                description: "Take HTML file from testing/html-checks/html"
                required: true
                type: boolean
                default: true
            verbose:
                description: "Adds more debug statements"
                type: boolean
                required: false
                default: false


    workflow_call:
        inputs:
            use-cache:
                description: "Use the cache"
                required: true
                type: boolean
                default: false
            verbose:
                description: "Adds more debug statements"
                type: boolean
                required: false
                default: false

# Do something like Github CLI command to get array of changed filenames from PR
# First check if there's any .html files in the array. If there isn't exit early with success
# To really do that though maybe have two jobs: "html-exists", "cache-experiment-job"
#  cache-experiment-job --> if html-exists.outputs.there-are-html-files == "true"
env:
    GH_TOKEN: ${{ secrets.github_token }}

jobs:

    html-exists:
        name: "Check for HTML files"
        runs-on: ubuntu-latest
        env:
            PR_NUMBER: ${{ github.event.pull_request.number }}
            EVENT_NAME: ${{ github.event_name }}
        outputs: 
            # General format steps.<step-id>.outputs.<var written to GITHUB_OUTPUT>
            html-files-present: ${{ steps.check-for-html-files.outputs.html-files-present }}
            html-filenames: ${{ steps.check-for-html-files.outputs.html-filenames }}

        steps:

            - name: "Checkout repo"
              uses: actions/checkout@v4

            - name: "Manual trigger: Use dummy HTML"
              if: inputs.use-dummy-html == true
              run: |
                echo "Setting PR_NUMBER to 9 (has 2 .html files)"
                echo "PR_NUMBER=9" >> $GITHUB_ENV

            - name: "Give exec permissions to scripts"
              run: chmod a+x ./scripts/html-checks/*.sh ./scripts/html-checks/*.py

            # TODO change this to a script. Arg: PR_NUM, inputs.verbose, github.event_name
            - name: "Assess PR Changed Files for *.html"
              id: check-for-html-files
              run: |
                bash ./scripts/html-checks/check-for-html-files.sh $PR_NUMBER ${{ inputs.verbose }} ${{ github.event_name }}

    cache-experiment-job:
        name: "HTML Checks (example of cache usage)"
        runs-on: ubuntu-latest
        needs: html-exists
        if: needs.html-exists.outputs.html-files-present == 'true'
        steps:
            
            - name: "Checkout repo"
              uses: actions/checkout@v4

            - name: "Echo vars"
              run: |
                echo "output!html-exists = ${{ needs.html-exists.outputs.html-filenames }}"
                echo "output!html-files-present = ${{ needs.html-exists.outputs.html-files-present }}"

            # actions/setup-python makes a virtual environment for you and it's already active, so usually no need to do things like "python m venv .venv" or "source .venv/bin/activate"
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"

            # Caches persist for 7 days. TODO move this comment somewhere I dunno where else to put it 
            - name: "Use actions/cache to speed up dependency installation"
              id: cache-dependencies
              if: inputs.use-cache
              uses: actions/cache@v4
              with: 
                #  ~/.cache/pip is where TODO
                path: ~/.cache/pip
                key: stop-asking-me-to-fill-all-this-in

            # The time duration of this step should decrease drastically when using a cache
            - name: Install dependencies
              run: |
                echo "TBD"
                # pip install -r ./scripts/html-checks/requirements.txt

            - name: "Script: Check each HTML file's TODOs have corresponding story"
              run: |
                echo "blablbala"
                # You could either feed whole  ".html,.html,..."string in or do a loop here and subject each to script
                # python html-checks/main.py