name: Caller Permission Test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-job:
    uses: ./.github/workflows/reusable-workflow-test.yml
    name: "Test job for caller permissions"
    permissions:
        contents: read