name: Caller Permission Test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
    bs-job:
        name: "BS job"
        runs-on: ubuntu-latest
        steps:
            - name: Write hi
              run: echo "hi"

    test-job:
        uses: ./.github/workflows/reusable-workflow-test.yml
        name: "Test job for caller permissions"
        permissions:
            contents: read