name: Non-main workflow CALLER

on:
  workflow_dispatch:
    inputs:
        perform-server-check-caller:
            # 
            description: "Reusable workflow: Do the server check"
            required: true
            type: boolean
            default: true
        called-by-caller-workflow:
            description: "Called by workflow"
            type: boolean
            default: true
            required: true
        # feature-branch:
        #     Readers of 'Triggering a Github Actions Workflow Without Merging Into The Default Branch: A Guide', you can ignore this input.
        #     # TODO: The feature branch that contains the workflow that has not been merged into the default branch.
        #     description: "Branch the workflow resides in"
        #     required: false
        #     type: string

jobs:
    echo-per-input:
        name: "Echo inputs"
        runs-on: ubuntu-latest
        steps:
            - name: 'Echo relevant vars'
              run: echo "inputs.perform-server-check-caller = ${{ inputs.perform-server-check-caller }}"

    non-main-workflow-caller:
        name: 'Non-main workflow caller Job'
        # If you're forking this, replace the ref (text after '@') with your feature branch
        uses: org-mushroom-kingdom/ttn-workflows/.github/workflows/non-main-workflow.yml@feature/matt-test-workflow-without-main-merge
        with: 
            perform-server-check: ${{ inputs.perform-server-check-caller }}

