# This comment is a dummy change only visible in feature/matt-this-branch-used-to-trigger-n-m-w-via-pull-request!!!!!!

name: Non-main workflow

# Scenario: Say we want to do a basic server connectivity test before deploying to them. Toad Town News is strict with merges to main during certain time periods; this is one of those times.
# In other words, the workflow needs to be tested without being merged to the default branch (main)
# There are multiple ways to do this, thus the variety of triggers.

# WITH THAT IN MIND, treat this file as if it was NOT merged to main/the default branch (I'm merging it to main to keep things tidy and for archival purposes). 
# Treat the comments in the same way. (I've tried to use the phrase "When the workflow isn't merged to main" diligently)
# The branch this workflow was originally tested on was feature/matt-test-workflow-without-main-merge. If you're using this file to test, make sure to do a find and replace.
# TODO ELABORATE?

# The business logic of this workflow is thus:
# Checkout the repo.
# IF env.PERFORM_SERVER_CHECK is true
# Call a script (server-checks.sh):
#     For each server in /deploys/server-list.csv: Make GET request to server, print out the server and HTTP status code for each server in a .csv list 
#     If HTTP code is 200, print out in green. If HTTP code is NOT 200, print that out in red.
# Such logic can later be elaborated upon to make programmatic deploy decisions (ex. if server X is down, continue with deploy. If server Y is down, don't) 
on:
  
  # push:
    # When the workflow isn't merged to main, you don't have to specify the feature branch the workflow is on.
    # This is because Github evaluates only evalutes workflow files that exist in the branch receiving the push. (See dev.solve)

    # You can still include branches: though if you want to make it more explicit or serve as a reminder.
    # branches: [feature/matt-test-workflow-without-main-merge]
    # When the workflow isn't merged to main, if you want to fire it whenever a push occurs, DON'T use the below line
    # The paths: key is for fine-tuning. For this file, we limit the workflow to fire under a push ONLY when that push includes a change to './github/workflows/non-main-workflow.yml'
    # paths: 
      # - '.github/workflows/non-main-workflow.yml'


  # The default types for pull_request are open, synchronize, and reopen. Thus those are the types we are using since none are specified.
  # When the workflow isn't merged to main, to get the workflow to fire using this trigger you have to first open a pull request (PR) 
  # with the target (base) branch being the feature branch you have the workflow on   
  # The initial creation of the PR is the "open" trigger and thus fires off the workflow
  # To perform further firings of the workflow with a vanilla pull_request trigger, you can:
  # - Open another PR with the target branch being the feature branch you have the workflow on ("open" trigger)
  # - While the PR is open, make a commit to the source branch of the PR ("synchronize" trigger) *This is the easiest way.
  # - Close and reopen the PR ("reopen" trigger)
  pull_request:
    # When the workflow isn't merged to main, you don't have to specify the feature branch the workflow is on.
    # This is because the pull_request trigger only evalutes workflow files that exist in the target (base) branch of the PR
    # You can still include branches: though if you want to make it more explicit or serve as a reminder.
    
    # When the workflow isn't merged to main, if you want to fire it whenever a push occurs, DON'T use the below paths: key and its child (docs/**)
    # The paths: key will see if the changed files in a pull request match a certain glob pattern. You can thus fine-tune pull_request activity by
    # ensuring the workflow only fires when certain files have been changed.
    # For example, if the below lines are commented IN and you make a commit on the source branch in a PR that does NOT fall under the glob 'docs/**', the workflow will NOT be triggered.
    # paths: 
    #   - 'docs/**'


  # workflow_dispatch can be triggered in one of the following ways:
  # - via Github Actions UI (IF the workflow has been merged into the default branch)
  # When the workflow isn't merged to main, you can't use the UI. However, you can use the two options below regardless of whether the workflow has been merged to main or not.
  # - via an API call:
  #     Make an API call to the path https://api.github.com/repos/<OWNER>/<REPO>/actions/workflows/<workflow-filename.yml>/dispatches
  #     See /README.md for auth and header info.
  #     See /docs/payload-for-non-main-workflow.json for details on body to send.
  # - via Github CLI call:
  #     For this scenario, make the CLI call with inputs (-f tag). 
  #     gh workflow run non-main-workflow.yml --ref <branch-name> -f notes="Triggered by Github CLI call" -f triggered-by-api=true -f perform-server-check=<true or false>
  #     See example call below 
  #     gh workflow run non-main-workflow.yml --ref feature/matt-test-workflow-without-main-merge -f notes="Triggered by Github CLI call" -f triggered-by-api=true -f perform-server-check=false

  workflow_dispatch:
    inputs:
      notes:
        description: "Gives additional context about the workflow_dispatch call."
        required: false
        type: string
        default: "No notes. It's possible this was triggered via the Github Actions UI IF this workflow has been merged into the default branch"
      # Set this to true in API calls to help determine how workflow_dispatch was triggered. (Serves as a supplement to the 'notes' input above.)
      # (This isn't strictly required, but if the workflow gets merged in to the default branch and you want to use the UI to run it AND API calls, 
      # this helps determine the nature of the workflow_dispatch trigger.)
      # Set this to true in Github CLI calls as well, since Github CLI is essentially a wrapper for the Github API.
      triggered-by-api:
        description: "Is true if called by API"
        required: true
        type: boolean
        default: false
      # For this particular scenario, we're testing several different ways to trigger a workflow that hasn't been merged into main
      # Thus, we often may care more about the call itself and not always desire to execute the script.
      perform-server-check:
        description: "Do the server check"
        required: true
        type: boolean
        default: true

  workflow_call:
    inputs:
      # This functions and is named exactly the same as the workflow_dispatch version. 
      perform-server-check:
        description: "Do the server check"
        required: true
        type: boolean
        default: true
      called-by-caller-workflow:
        type: boolean
        default: true

jobs:
  non-main-job:
    name: "Non-main job"
    runs-on: ubuntu-latest
    env:
      # ANSI colors
      YELLOW: "\e[33m"
      ENDCOLOR: "\e[0m"
      # This can be set to false if calling this workflow with workflow_dispatch or workflow_call (see step 'inputs: Set PERFORM_SERVER_CHECK to false if specified')
      PERFORM_SERVER_CHECK: true
      

    steps:
        
        - name: Checkout repo
          # Note: regarding workflow_call, for this scenario our only caller workflow is in the same repository as non-main-workflow.yml
          # If there was a caller workflow in a different repo, a token would have to be passed in and used as part of actions/checkout 
          uses: actions/checkout@v4
          with:
            ref: feature/matt-test-workflow-without-main-merge

        - name: Echo workflow trigger, activity type (if exists)
          run: |
            echo -e "This workflow was triggered by the ${{ env.YELLOW }}${{ github.event_name }}${{ env.ENDCOLOR }} event"
            [[ "${{ inputs.called-by-caller-workflow }}" == true ]] && echo "The non-main-workflow was triggered by ${{ env.YELLOW }}workflow_call${{ env.ENDCOLOR }}. The caller workflow was triggered by the above event." || :
            [[ "${{ inputs.called-by-caller-workflow }}" == true ]] && echo "Caller workflow (github.event.workflow) = ${{ github.event.workflow }}" || :
            [[ "${{ github.event.action }}" != "" ]] && echo -e "This workflow was triggered by the event's activity type ${{ env.YELLOW }}${{ github.event.action }}${{ env.ENDCOLOR }}" || :

        - name: "workflow_dispatch: Read inputs"
          if: github.event_name == 'workflow_dispatch' && inputs.called-by-caller-workflow == false
          run: |
            echo "inputs.notes: ${{ env.YELLOW }}${{ inputs.notes }}${{ env.ENDCOLOR }}"
            echo "inputs.triggered-by-api: ${{ env.YELLOW }}${{ inputs.triggered-by-api }}${{ env.ENDCOLOR }}"
            echo "inputs.perform-server-check: ${{ env.YELLOW }}${{ inputs.perform-server-check }}${{ env.ENDCOLOR }}"
        
        - name: Grant 'runner' user exec permissions
          run: chmod u+x ./scripts/server-checks.sh

        - name: "inputs: Set PERFORM_SERVER_CHECK to false if specified"
          if: github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' 
          run: |
            # This can refer to the input provided from EITHER workflow_dispatch or workflow_call since they share the same name
            if [[ "${{ inputs.perform-server-check }}" == "false" || "${{ inputs.perform-server-check }}" == "" ]]
            then
              echo "PERFORM_SERVER_CHECK=false" >> $GITHUB_ENV
            fi

        - name: Perform server checks
          # You need quotes here because environmental variables are treated as strings 
          if: ${{env.PERFORM_SERVER_CHECK == 'true'}}
          run: ./scripts/server-checks.sh
