name: Runner Diagnostics Log Test

on:
  workflow_dispatch:
    inputs:
      env_debug:
        description: 'Set to true to enable runner diagnostics logs'
        type: boolean
        required: false
env:
  ACTIONS_RUNNER_DEBUG: ${{ github.event.inputs.env_debug }}

jobs:
  diagnostic_state:
    runs-on: ubuntu-latest
    steps:
      - name: Detect vars.ACTIONS_RUNNER_DEBUG
        run: echo "vars.ACTIONS_RUNNER_DEBUG = ${{ vars.ACTIONS_RUNNER_DEBUG }}!"
      
      - name: Detect env.ACTIONS_RUNNER_DEBUG
        run: |
            echo "env.ACTIONS_RUNNER_DEBUG = ${{ env.ACTIONS_RUNNER_DEBUG }}!"
            if [ "${{ env.ACTIONS_RUNNER_DEBUG }}" == "true" ]
            then
                echo "You should see additional diagnostic logs in this workflow run!"
            fi