name: Runner Diagnostics Log Test

on:
  workflow_dispatch:
    inputs:
      env_debug:
        description: 'Set to true to enable runner diagnostics logs'
        type: boolean
        required: false
env:
    # ACTIONS_RUNNER_DEBUG: ${{ github.event.inputs.env_debug }}
    ACTIONS_RUNNER_DEBUG: true
    YELLOW: "\e[33m"
    ENDCOLOR: "\e[0m"

jobs:
  diagnostic_state:
    name: Diagnostic Logs
    runs-on: ubuntu-latest
    steps:
      - name: Detect vars.ACTIONS_RUNNER_DEBUG
        run: | 
            echo -e "vars.ACTIONS_RUNNER_DEBUG = ${YELLOW}${{ vars.ACTIONS_RUNNER_DEBUG }}${ENDCOLOR}!"
            if [ "${{ vars.ACTIONS_RUNNER_DEBUG }}" == "true" ]
            then
                echo "You should see additional diagnostic logs in this workflow run!"
            fi
      - name: Detect env.ACTIONS_RUNNER_DEBUG
        run: |
            echo -e "env.ACTIONS_RUNNER_DEBUG = ${YELLOW}${{ env.ACTIONS_RUNNER_DEBUG }}${ENDCOLOR}!"
            if [ "${{ env.ACTIONS_RUNNER_DEBUG }}" == "true" ]
            then
                echo "You should see additional diagnostic logs in this workflow run!"
            fi