name: Add 'team-a' label!!

on:
  pull_request:
    types: [opened,synchronize]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  pull-requests: write

jobs:
  add-label:
    name: "Add 'team-a' label when source branch name contains team-a"
    runs-on: ubuntu-latest
    steps:
      
      - name: Add team-a label
        if: contains(github.head_ref, 'team-a')
        run: gh pr edit ${{ github.event.pull_request.number }} --add-label "team-a" --repo ${{ github.repository }}

      - name: Temp fail
        run: exit 1