name: Upload Example Artifact

on:
  workflow_dispatch:

  # push:

jobs:
  make-and-upload-artifact:
    runs-on: ubuntu-latest
    steps:
        - name: Create example artifact
          run: |
            echo "Hello!" > example-artifact.txt

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: example-artifact
            path: example-artifact.txt
        
        # Uses head_commit instead of commits array
        - name: Get latest commit message
          run: echo "Commit message = ${{ github.event.head_commit.message }}"
